### ISSUE TITLE
Computer/Server requirements

### ISSUE THREAD

**Issue by rafaeltiveron** [brianjimenez/lightdock#12]
Good afternoon,

Which are the requirements to run LightDock (ex: MEM, CPU, etc)?

**Comment by brianjimenez** [comment]
Hi,
Requirements heavily depend on the different values given to number of swarms, glowworms per swarm, simulation steps, receptor and ligand size (number of atoms), scoring function and residue restraints given. For example, few residue restraints on receptor side reduces the number of swarms to explore, usually in the scale of minutes for a complete simulation. If you are capable of delimiting your system variables, we could give you a better estimation.

You can also have a look to the 4G6M example where there is information about CPU cores used, complex size, restraints and CPU time: https://brianjimenez.github.io/lightdock/4G6M.html

**Comment by rafaeltiveron** [comment]
Thanks, man. I'll have a look.
