### ISSUE TITLE
pyDockLite?

### ISSUE THREAD

**Issue by rafaeltiveron** [brianjimenez/lightdock#14]
Hi Brian again

I'm new in docking protein and from biology area, learning starting things yet..

Why I can't find/use pyDockLite scoring function in LightDock?

**Comment by brianjimenez** [comment]
Hi,
pyDockLite function corresponds to the internal name of "cpydock". You can find the rest of implemented scoring functions [here](../tree/master/lightdock/scoring). 
If you use `cpydock`, please follow the instructions on how to install freesasa (required library).
