### ISSUE TITLE
./run_tests.sh: line 38: nosetests-2.7: command not found

### ISSUE THREAD

**Issue by ccgauvin94** [brianjimenez/lightdock#23]
After install, when trying to run the tests, I get the following error: 
./run_tests.sh: line 38: nosetests-2.7: command not found

## Expected Behavior
Tests should run

## Current Behavior
Trying ./run_tests.sh in the lightdock home results in the following error:
`./run_tests.sh: line 38: nosetests-2.7: command not found`

## Steps to Reproduce
Followed install guide. Ran:
`pip install numpy scipy cython biopython nose nose2 mpi4py ProDy pyparsing`
cloned and built lightdock without any errors, added the paths to my .bashrc, and ran the setup.sh file for high intensive calculations. When I run the tests, I get that error. 

## Context (Environment)
Running on Manjaro

**Comment by brianjimenez** [comment]
Problem is `nosetests-2.7` seems to not be in the path. Try executing `/usr/bin/nosetests-2.7` or `which nosetests-2.7` to locate it. You can after add that path to your `PATH` environment variable or modifying `run_tests.sh` to point to the good location of `nosetests-2.7`.
