### ISSUE TITLE
Problem with Pip3 Install

### ISSUE THREAD

**Issue by ccgauvin94** [brianjimenez/lightdock#25]
## Expected Behavior
lightdock should install and place binaries or .py files properly

## Current Behavior
`/usr/local/lib/python3.7/dist-packes/lightdock` has no binaries or lightdock.py file. Instead, `lightdock3.py` and `lightdock3_setup.py` are located in `/usr/local/bin` and when trying to run `setup.json`, the script cannot find the setup files. 

## Steps to Reproduce
Used the command `sudo pip3 install lightdock` on Ubuntu Server 19.10, received no installation errors. 

## Context (Environment)
Renders the software unusable because the python file can't find the install directory. 

Output of `sudo pip3 show lightdock`:

> Name: lightdock
> Version: 0.8.0a1
> Summary: A macromolecular docking framework
> Home-page: https://lightdock.org/
> Author: None
> Author-email: None
> License: GPLv3 License
> Location: /usr/local/lib/python3.7/dist-packages
> Requires: freesasa, biopython, scipy, pyparsing, cython, prody, numpy
> Required-by:

**Comment by brianjimenez** [comment]
Hi,
Note that this is the repository for legacy `Python 2.7` version, which does not support the installation via `pip`.
If you install with `pip3 install lightdock` better use `virtualenv` to avoid system-wide installations.

Commands are correct for Python 3 as they have been renamed to avoid confusions: `lightdock3.py` and `lightdock3_setup.py`. Please check source code here (https://github.com/lightdock/lightdock) and tutorials here: https://lightdock.org/tutorials/

**Comment by brianjimenez** [comment]
Installed Ubuntu Server 19.10 in a virtual machine and followed the instructions to install `lightdock` from https://github.com/lightdock/lightdock

Setup and docking worked smoothly:

<img width="886" alt="lightdock_ubuntu_server" src="https://user-images.githubusercontent.com/4330278/68377337-7330b100-014a-11ea-89a7-01e8ef7019df.png">
